# Generated by Django 4.0.4 on 2022-08-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
