# Generated by Django 4.0.4 on 2022-08-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_alter_userfile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
