# Generated by Django 4.0.4 on 2022-08-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_alter_userfile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to='files/%Y%m%d'),
        ),
    ]
