# Generated by Django 4.0.3 on 2022-05-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_alter_userfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name='userfile',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='hits', to='file.ipaddress'),
        ),
    ]
